#!/bin/bash
# Microwatt Integration Script
# This script integrates QNNA accelerator with Microwatt OpenPOWER CPU
# Author: TechJoe96

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MICROWATT_REPO="${MICROWATT_REPO:-https://github.com/antonblanchard/microwatt.git}"
# Default to dependencies/microwatt in project root
MICROWATT_DIR="${MICROWATT_DIR:-$PROJECT_ROOT/dependencies/microwatt}"

echo "========================================="
echo "  Microwatt + QNNA Integration Script"
echo "========================================="
echo ""

# Check if Microwatt directory exists
if [ ! -d "$MICROWATT_DIR" ]; then
    echo "Microwatt directory not found: $MICROWATT_DIR"
    echo ""
    echo "Options:"
    echo "  1. Clone Microwatt:"
    echo "     git clone $MICROWATT_REPO $MICROWATT_DIR"
    echo ""
    echo "  2. Or set MICROWATT_DIR environment variable:"
    echo "     export MICROWATT_DIR=/path/to/microwatt"
    echo ""
    read -p "Would you like to clone Microwatt now? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Cloning Microwatt..."
        CLONE_DIR="$(dirname "$MICROWATT_DIR")"
        if [ ! -d "$CLONE_DIR" ]; then
            echo "Error: Directory does not exist: $CLONE_DIR"
            echo "Please create the directory first or set MICROWATT_DIR to a valid path"
            exit 1
        fi
        cd "$CLONE_DIR"
        git clone "$MICROWATT_REPO" "$(basename "$MICROWATT_DIR")"
        echo "✓ Microwatt cloned to: $MICROWATT_DIR"
    else
        echo ""
        echo "Please set MICROWATT_DIR environment variable and run again:"
        echo "  export MICROWATT_DIR=/path/to/microwatt"
        echo "  ./scripts/integrate_microwatt.sh"
        exit 1
    fi
fi

MICROWATT_DIR="$(cd "$MICROWATT_DIR" && pwd)"
echo "Microwatt directory: $MICROWATT_DIR"
echo "Project directory: $PROJECT_ROOT"
echo ""

# Step 1: Copy QNNA RTL files to Microwatt verilog directory
echo "Step 1: Copying QNNA RTL files to Microwatt..."
MICROWATT_VERILOG_DIR="$MICROWATT_DIR/verilog/rtl"
mkdir -p "$MICROWATT_VERILOG_DIR"

# Copy QNNA modules
cp "$PROJECT_ROOT/rtl/qnna_top.v" "$MICROWATT_VERILOG_DIR/"
cp "$PROJECT_ROOT/rtl/qnna_wishbone.v" "$MICROWATT_VERILOG_DIR/"
cp "$PROJECT_ROOT/rtl/qnna_csr.v" "$MICROWATT_VERILOG_DIR/"
cp "$PROJECT_ROOT/rtl/qnna_mac_array.v" "$MICROWATT_VERILOG_DIR/"
cp "$PROJECT_ROOT/rtl/qnna_buffer.v" "$MICROWATT_VERILOG_DIR/"

echo "✓ QNNA RTL files copied to $MICROWATT_VERILOG_DIR"
echo ""

# Step 2: Create SoC integration file
echo "Step 2: Creating SoC integration file..."
cat > "$MICROWATT_VERILOG_DIR/microwatt_soc_with_qnna.v" << 'SOCEOF'
// Microwatt SoC with QNNA Accelerator
// This file integrates QNNA into Microwatt SoC
// Generated by integrate_microwatt.sh

module microwatt_soc_with_qnna (
    input wire clk,
    input wire rst,
    
    // UART
    input wire uart_rx,
    output wire uart_tx,
    
    // GPIO
    input wire [7:0] gpio_in,
    output wire [7:0] gpio_out,
    
    // Debug
    output wire [63:0] debug_pc,
    output wire debug_valid,
    
    // QNNA interrupt
    output wire qnna_irq
);

    // Microwatt SoC Wishbone signals (external I/O)
    wire [29:0] wb_ext_io_adr;
    wire [31:0] wb_ext_io_dat_w;
    wire [31:0] wb_ext_io_dat_r;
    wire [3:0] wb_ext_io_sel;
    wire wb_ext_io_cyc;
    wire wb_ext_io_stb;
    wire wb_ext_io_we;
    wire wb_ext_io_ack;
    wire wb_ext_io_stall;
    
    // QNNA Wishbone signals
    wire qnna_wb_cyc;
    wire qnna_wb_stb;
    wire qnna_wb_we;
    wire [31:0] qnna_wb_adr;
    wire [31:0] qnna_wb_dat_w;
    wire [31:0] qnna_wb_dat_r;
    wire [3:0] qnna_wb_sel;
    wire qnna_wb_ack;
    wire qnna_wb_err;
    
    // Address decode for QNNA (0x80000000 - 0x80000FFF)
    localparam QNNA_BASE = 32'h80000000;
    localparam QNNA_END  = 32'h80000FFF;
    
    assign qnna_wb_cyc = wb_ext_io_cyc && 
                         (wb_ext_io_adr >= QNNA_BASE[31:2]) && 
                         (wb_ext_io_adr <= QNNA_END[31:2]);
    assign qnna_wb_stb = wb_ext_io_stb && qnna_wb_cyc;
    assign qnna_wb_we = wb_ext_io_we;
    assign qnna_wb_adr = {wb_ext_io_adr, 2'b00};
    assign qnna_wb_dat_w = wb_ext_io_dat_w;
    assign qnna_wb_sel = wb_ext_io_sel;
    
    // Multiplex QNNA response with other peripherals
    assign wb_ext_io_dat_r = qnna_wb_ack ? qnna_wb_dat_r : 32'h0;
    assign wb_ext_io_ack = qnna_wb_ack;  // TODO: Add other peripherals
    assign wb_ext_io_stall = 1'b0;
    
    // Instantiate Microwatt SoC (converted from VHDL)
    // Note: This requires VHDL-to-Verilog conversion of Microwatt
    // For now, this is a placeholder structure
    // In real implementation, use the actual Microwatt SoC module
    
    // Placeholder for Microwatt SoC
    // microwatt_soc soc_inst (
    //     .clk(clk),
    //     .rst(rst),
    //     .wb_ext_io_adr(wb_ext_io_adr),
    //     .wb_ext_io_dat_w(wb_ext_io_dat_w),
    //     .wb_ext_io_dat_r(wb_ext_io_dat_r),
    //     .wb_ext_io_sel(wb_ext_io_sel),
    //     .wb_ext_io_cyc(wb_ext_io_cyc),
    //     .wb_ext_io_stb(wb_ext_io_stb),
    //     .wb_ext_io_we(wb_ext_io_we),
    //     .wb_ext_io_ack(wb_ext_io_ack),
    //     .wb_ext_io_stall(wb_ext_io_stall),
    //     .uart_rx(uart_rx),
    //     .uart_tx(uart_tx),
    //     .gpio_in(gpio_in),
    //     .gpio_out(gpio_out),
    //     .debug_pc(debug_pc),
    //     .debug_valid(debug_valid)
    // );
    
    // TODO: Connect actual Microwatt SoC
    // For now, tie off signals
    assign debug_pc = 64'h0;
    assign debug_valid = 1'b0;
    assign gpio_out = 8'h0;
    
    // Instantiate QNNA
    qnna_top #(
        .ADDR_WIDTH(32),
        .DATA_WIDTH(32),
        .MAC_SIZE(4),
        .BUFFER_DEPTH(256)
    ) qnna_inst (
        .wb_clk_i(clk),
        .wb_rst_i(rst),
        .wb_adr_i(qnna_wb_adr),
        .wb_dat_i(qnna_wb_dat_w),
        .wb_dat_o(qnna_wb_dat_r),
        .wb_we_i(qnna_wb_we),
        .wb_sel_i(qnna_wb_sel),
        .wb_stb_i(qnna_wb_stb),
        .wb_cyc_i(qnna_wb_cyc),
        .wb_ack_o(qnna_wb_ack),
        .wb_err_o(qnna_wb_err),
        .irq_o(qnna_irq),
        .vdd(1'b1),
        .vss(1'b0)
    );

endmodule
SOCEOF

echo "✓ SoC integration file created"
echo ""

# Step 3: Create integration documentation
echo "Step 3: Creating integration documentation..."
cat > "$PROJECT_ROOT/docs/MICROWATT_INTEGRATION.md" << 'DOCEOF'
# Microwatt Integration Guide

## Overview

This guide explains how to integrate QNNA accelerator with Microwatt OpenPOWER CPU.

## Integration Steps

### 1. Prerequisites

- Microwatt repository cloned
- QNNA RTL files available
- VHDL-to-Verilog conversion tools (if needed)

### 2. Integration Script

Run the integration script:

```bash
cd openpower-qnna-project
./scripts/integrate_microwatt.sh
```

This will:
- Copy QNNA RTL files to Microwatt verilog directory
- Create SoC integration file
- Set up address mapping

### 3. Address Map

QNNA is mapped to:
- **Base Address**: `0x80000000`
- **Size**: `4KB` (0x80000000 - 0x80000FFF)
- **Register Map**: See `README.md` for register offsets

### 4. Wishbone Interface

QNNA connects to Microwatt's external I/O Wishbone bus:
- Master: Microwatt CPU
- Slave: QNNA accelerator
- Protocol: Wishbone B4

### 5. Interrupts

QNNA can generate an interrupt when computation completes:
- Connected to Microwatt's external interrupt input
- Interrupt number: TBD (depends on Microwatt configuration)

## Next Steps

1. **VHDL-to-Verilog Conversion**: Convert Microwatt SoC to Verilog (if needed)
2. **Integration Testing**: Run SoC-level testbenches
3. **Software Driver**: Create QNNA driver for Microwatt
4. **OpenFrame Integration**: Integrate into OpenFrame project wrapper

## Testing

See `docs/SOC_TESTBENCH.md` for SoC-level testbench instructions.

## Troubleshooting

### Issue: Microwatt not found
**Solution**: Set `MICROWATT_DIR` environment variable:
```bash
export MICROWATT_DIR=/path/to/microwatt
```

### Issue: Address conflicts
**Solution**: Adjust QNNA base address in integration file

### Issue: Wishbone protocol mismatch
**Solution**: Verify Wishbone B4 compliance of both modules
DOCEOF

echo "✓ Integration documentation created"
echo ""

# Step 4: Summary
echo "========================================="
echo "  Integration Complete!"
echo "========================================="
echo ""
echo "Files created/modified:"
echo "  ✓ QNNA RTL files copied to: $MICROWATT_VERILOG_DIR/"
echo "  ✓ SoC integration file: $MICROWATT_VERILOG_DIR/microwatt_soc_with_qnna.v"
echo "  ✓ Documentation: $PROJECT_ROOT/docs/MICROWATT_INTEGRATION.md"
echo ""
echo "Next steps:"
echo "  1. Review integration file: $MICROWATT_VERILOG_DIR/microwatt_soc_with_qnna.v"
echo "  2. Convert Microwatt VHDL to Verilog (if needed)"
echo "  3. Run SoC testbench: see docs/SOC_TESTBENCH.md"
echo "  4. Integrate with OpenFrame: see scripts/integrate_openframe.sh"
echo ""

